name: Test
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: tix/src/tix

    - name: Get dependencies
      run: make deps

    - name: Test
      run: make test
